sut:
    build: .
    environment:
        - BASH_ENV=~/.bashrc
    command: /bin/bash -c "
        git clone git://git.yoctoproject.org/poky
        && source poky/oe-init-build-env
        && bitbake --dry-run core-image-minimal" 
